config/routes.rb
Rails.application.routes.draw do

  
   root 'pages#index'
   get 'sessions/new', to: 'sessions#new'
   get 'about' , to: 'pages#about'
   get 'contact' , to: 'pages#contact'
   get 'register' , to: 'customers#new'
   post 'register' , to: 'customers#create'
   get 'login',   to: 'sessions#new'
   post 'login',   to: 'sessions#create'
   delete 'logout',  to: 'sessions#destroy'

   resources :customers, except: [:new]
   resources :customers
   resources :sessions

end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

# Prevent CSRF attacks by raising an exception.

# For APIs, you may want to use :null_session instead.

protect_from_forgery with: :exception

helper_method :current_customer, :logged_in?

def current_customer

@current_customer ||= Customer.find(session[:customer_id]) if session[:customer_id]

end

def logged_in?

!!current_customer

end

def require_customer

if !logged_in?

flash[:danger] = "You must be logged in to perform that action"

redirect_to root_path

end

end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
    def create
        cparams = customer_params

        if cparams[:password] != cparams[:password_confirmation]
            raise "oh no"
        end

        customer = Customer.new(cparams.except(:password_confirmation)) # Not the final implementation!
        customer.save!
        redirect_to customer
    end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
     @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
        params.require(:customer).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def index
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        params.require(:session)
        customer = Customer.find_by(:email => params[:session][:email])
        if customer and customer.password == params[:session][:password]
            redirect_to customer
        else
            render status: :forbidden
        end
    end

    def user_params
        params.require(:customer).permit(
            :name, :email, :password, :password_confirmation)
    end

    def destroy
        session[:customer_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>

      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.password %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="row">
  <div class="col-xs-offset-4 col-xs-4">
   <h1 align="center">Sign up</h1>
    <%= form_for(:customer, url: register_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>
      <%= f.submit class: 'btn btn-primary btn-sm' %>
     
    <% end %>
 </div>
</div>
  
<div class="col-xs-4 col-xs-offset-8">
<%= link_to '[Home]', root_path %>
</div>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @customer.password %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/_footer.html.erb
<div class="container">

<footer class="footer">

<small>

 

</small>

<nav>

<ul>

<li><%= link_to "About", about_path %></li>

</ul>

</nav>

</footer>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header navbar-default">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>

<%= link_to "Reservation Hotel System", '#', id: "logo" %>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

<ul class="nav navbar-nav ">
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "login", login_path %></li>
<li><%= link_to 'New Customer', register_path %></li>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
 <ul class="nav navbar-nav navbar-right"> <ul class="nav navbar-nav navbar-right">

<% if logged_in? %>

<li><%= link_to 'Log out', logout_path, method: :delete %></li>

<li class="dropdown">

<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<span class="caret"></span></a>

<ul class="dropdown-menu">

<li><%= link_to "Edit your profile", edit_customer_path(current_customer) %></li>

<li><%= link_to "View your profile", customer_path(current_customer) %></li>



<li role="separator" class="divider"></li>

<li><a href="#">Separated link</a></li>

</ul>

</li>

<% else %>

<li><%= link_to 'Log in', login_path %></li>

<li><%= link_to 'Sign up', register_path %></li>

<% end %>

</ul>
</ul>
</nav>
<body>
</body>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<html>


<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<%= csrf_meta_tags %>


 
 <body>
     
     

 <%= render 'layouts/navigation' %>
 <h3 align="center">About US</h3>






</body>

</html>

app/views/pages/contact.html.erb
<html>


<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<%= csrf_meta_tags %>


 
 <body>
     
     

 <%= render 'layouts/navigation' %>
<h3 align="center">Contact US</h3>
<br>

<address align="center">
  <strong>Hotel, Inc.</strong><br>
  1355 Market Street, Suite 900<br>
  San Francisco, CA 94103<br>
  <abbr title="Phone">P:</abbr> (123) 456-7890
</address>

<address align="center">
  <strong>Hotel</strong><br>
  <a href="mailto:#">Hotel@example.com</a>
</address>




</body>

</html>
 

app/views/pages/index.html.erb
<html>
 <head>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
 
</head>

<body>


 <%= render 'layouts/navigation' %>
 <h3 align="center">Home</h3>


<div class="container">

<%= yield %>

</div>



</body>

</html>

app/views/pages/register.html.erb
<html>


<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>


 
 <body>
     
     

 <%= render 'layouts/navigation' %>
<h3 align="center">Registration Form</h3>






</body>

</html>
 
 